/*CRIAÇÃO DE TABELAS*/


/*TABLE  USUARIO
CREATE TABLE TB_USUARIO_CLIENTE(
ID INT NOT NULL AUTO_INCREMENT, 
RG INT NOT NULL PRIMARY KEY ,
NOME VARCHAR (30),
EMAIL VARCHAR (100),
TELEFONE VARCHAR (30),
ENDERECO VARCHAR (30),
NUMERO_ENDERECO INT,
BAIRRO VARCHAR (30),
CIDADE VARCHAR (30),
KEY (ID)
);
*/
/*TABLE PET
CREATE TABLE TB_PET(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
RACA VARCHAR (30),
PORTE VARCHAR (10),
SEXO CHAR (1),
NOME VARCHAR (30),
DONO int,
FOREIGN KEY (DONO) REFERENCES  TB_USUARIO_CLIENTE(RG)
);
*/

/*TABLE FUNCIONARIO
CREATE TABLE TB_FUNCIONARIO (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR (30),
CARGO VARCHAR (30),
ADMIN INT (1)
);
*/

/*TABLE PRODUTOS EM ESTOQUE
CREATE TABLE TB_ESTOQUE_PRODUTOS(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESCRICAO_PRODUTO VARCHAR (30),
PRECO_COMPRA FLOAT,
PRECO_VENDA FLOAT,
QUANT_ESTOQUE INT
)*/

/*TABLE SERVIÇOS DISPONIVEIS
CREATE TABLE TB_SERVICOS(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESCRICAO_SERVICO VARCHAR (30),
PRECO_SERVICO FLOAT
);
*/

/*TABLE SERVICOS REALIZADOS
CREATE TABLE TB_SERVICOS_REALIZADOS(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PET INT,
SERVICOS_UTILIZADOS VARCHAR (30),
ID_FUNCIONARIO INT,
VALOR_TOTAL FLOAT,
DATA DATE,
FOREIGN KEY (ID_PET) REFERENCES  TB_PET(ID),
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES  TB_FUNCIONARIO(ID)
);
*/

/*TABLE PRODUTOS VENDIDOS
CREATE TABLE TB_PRODUTOS_VENDIDOS(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_CLIENTE INT,
ID_FUNCIONARIO INT,
PRODUTOS_COMPRADOS VARCHAR(30),
PRECO_TOTAL FLOAT,
QUANT_ITENS INT,
DATA DATE,
FOREIGN KEY (ID_CLIENTE) REFERENCES  TB_USUARIO_CLIENTE(RG),
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES  TB_FUNCIONARIO(ID)
);
*/

/*TABLE RECEITA DE VENDAS
CREATE TABLE TB_VENDAS(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_FUNCIONARIO INT,
QUANT_SERVICOS INT,
QUANT_PRODUTOS INT,
VENDA_SERVICOS FLOAT,
VENDA_PRODUTOS FLOAT,
DATA DATE,
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES  TB_FUNCIONARIO(ID)
);
*/




