### Cadastrar Cliente
POST https://localhost:5001/ecommerceapi/cliente/cadastrar
Content-Type: application/json

{
    "CPF" : 18123,
    "NomeTutor" : "João",
    "Telefone" : "41998105689",
    "NomePet" : "Sanfona",
    "Especie": "Cachorro",
    "Idade": 10,
    "Porte": "Grande"
}