### Cadastrar Cliente
POST https://localhost:5001/ecommerceapi/cliente/cadastrar
Content-Type: application/json

{
    
    "NomeTutor" : "Pedro",
    "CPF" : 12345670,
    "Telefone" : "41998105689",
    "NomePet" : "Sanfona",
    "Especie": "Gato",
    "Idade": 10,
    "Porte": "Grande"
}


### Listar cliente
GET https://localhost:5001/ecommerceapi/cliente/listar


### Listar horarios
GET https://localhost:5001/ecommerceapi/agenda/listarHorario


### Adicionar horarios
POST https://localhost:5001/ecommerceapi/agenda/iniciar


