### Cadastrar Cliente
POST https://localhost:5001/ecommerceapi/cliente/cadastrar
Content-Type: application/json

{
    "CPF" : 1234567890123456,
    "NomeTutor" : "João",
    "Telefone" : "41998105689",
    "NomePet" : "Sanfona",
    "Especie": "Cachorro",
    "Idade": 10,
    "Porte": "Grande"
}


### Listar cliente
GET https://localhost:5001/ecommerceapi/cliente/listar


### Listar horarios
GET https://localhost:5001/ecommerceapi/agenda/listarHorario


### Adicionar horarios
POST https://localhost:5001/ecommerceapi/agenda/iniciar


