### Cadastrar serviço
POST https://localhost:5001/ecommerceapi/servicos/cadastrar
Content-Type: application/json

{
    "CPF": "78932",
    "Nome": "Calors",
    "Data": "2021-07-08",
    "Hora": 8,
    "Titulo": "Titulo",
    "Descricao": "Teste"
}



### Listar CPF -- Novo Agendamento
GET https://localhost:5001/ecommerceapi/cliente/listar

### Listar serviços
GET https://localhost:5001/ecommerceapi/servicos/listar

### Buscar serviço pelo ID
GET https://localhost:5001/ecommerceapi/servicos/buscar/1

### Alterar serviço
PUT https://localhost:5001/ecommerceapi/servicos/atualizar
Content-Type: application/json

{
    "Id": "1",
    "CPF": "147968",
    "Data": "2021-10-14",
    "Titulo": "Titulo",
    "Descricao": "Teste"
}

### Deletar serviço
DELETE https://localhost:5001/ecommerceapi/servicos/deletar/1